### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by qe660212** [Nota-NetsPresso/shortened-llm#13]
Hi~How can I reproduce the result of Table 3 in the paper?
Could you please share your CPT Retraining script?

**Comment by bokyeong1015** [comment]
Hi, thank you for your interest.

The pretraining script is currently regarded as an internal asset of our company. While we are exploring the possibility of its release, the timeline remains unclear. We appreciate your understanding and will reach out to you once we finalize our decision.
