### ISSUE TITLE
Can we extend it to instruct models ?

### ISSUE THREAD

**Issue by ambuje** [Nota-NetsPresso/shortened-llm#16]
Hi Team,

Amazing work and paper. 

Is it possible to prune Instruct models? If we prune base models then we do not have instruct capability.

Thank you,
Ambuje

**Comment by lifelongeeek** [comment]
Hi @ambuje 
> Is it possible to prune Instruct models?

Yes. You can apply the same block pruning algorithm on instruct models. However, you may need continued pre-train followed by instruction-tuning to make the pruned model having instruction-following capability.

**Comment by ambuje** [comment]
Hi @lifelongeeek ,

Thanks for your reply. 

Do you know if we have any examples of instructive models? If I am pruning meta-llama/Llama-3.1-70B-Instruct, why should we do continued pre-train? I can understand we can perform LORA (instruct dataset) to increase the accuracy. 

Am I missing something?

**Comment by lifelongeeek** [comment]
Although we did not publish the result for pruning the language model with instruction-following capability, we expect continued pre-train will be necessary for performance to recover to the original model.

If we prune the language model, wherever it came from (i.e., pre-trained, instruction-tuned, or alignment-tuned), it may somehow lose its abilities. [In our paper](https://arxiv.org/pdf/2402.02834), we empirically compared instruction-tuning VS. continued pre-train followed by instruction-tuning for the re-training method. Instruction-tuning alone cannot recover original model performance, especially for highly pruned models.

![image](https://github.com/user-attachments/assets/a95dad85-a5d1-49d1-a8eb-0f0e96e538e8)

**Comment by ambuje** [comment]
Thanks for the reply. 

I agree we need CPT for highly pruned models, I am talking about 20% pruning, for meta-llama/Llama-3.1-70B-Instruct. 

I'll try to prune meta-llama/Llama-3.1-70B-Instruct. Though need to see how we can prune instruct models. 

Thanks for your time :), do let me know if you guys try your experiment on chat/instruct models.
