### ISSUE TITLE
How can this method be applied to other large language models?

### ISSUE THREAD

**Issue by Franklin-L** [Nota-NetsPresso/shortened-llm#8]
I would like to apply this pruning method to other large models. How can I do that?

**Comment by bokyeong1015** [comment]
Hi, this repo supports Hugging Face Transformer-based LLMs by [implementing block pruning as weight copy](https://github.com/Nota-NetsPresso/shortened-llm/blob/467fd2ac36ae688349ea648ca244e47d3d5eef79/src/utils.py#L130) (i.e., defining a pruned architecture and copying unpruned weights into the architecture).

We would recommend changing [the Hugging Face model name in our example scripts](https://github.com/Nota-NetsPresso/shortened-llm/blob/467fd2ac36ae688349ea648ca244e47d3d5eef79/script/prune_vicuna-7b_crit-ppl.sh#L3-L4) and fixing bugs if needed.
